version: '3'

services:
  mm_raspberry:
    container_name: mm
    image: karsten13/mm_hyp:latest
    ports:
      - "8080:8080"
    volumes:
      - ~/magic_mirror/config:/opt/magic_mirror/config
      - ~/magic_mirror/modules:/opt/magic_mirror/modules
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc:/opt/vc/:ro
      - /run/systemd:/run/systemd
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix$DISPLAY
    network_mode: host
    entrypoint: /opt/magic_mirror/docker-entrypoint.sh "npm start"   
    restart: always

#  needed for module MMM-Systemtemperature:
#    volumes:
#      - /opt/vc:/opt/vc/:ro
#    environment:
#      LD_LIBRARY_PATH: /opt/vc/lib
#
#  needed for module MMM-NetworkScanner
#    network_mode: host
#
#  needed for module MMM-Systemtemperature and MMM-NetworkScanner
#    devices:
#      - /dev/vchiq
#
#  needed for module MMM-Remote-Control
#    volumes:
#      - /run/systemd:/run/systemd
